# Add changesets for Dependabot PRs
name: Dependabot Changesets
on:
  pull_request:
    # Trigger on creation (opened) and updates (synchronize)
    types: [opened, synchronize, reopened]
    # Do not trigger if ONLY files in .changesets are changed
    paths-ignore:
      - '.changesets/**'

permissions:
  contents: read

jobs:
  generate-changeset:
    runs-on: ubuntu-latest
    if: github.event.pull_request.user.login == 'dependabot[bot]' && github.repository == 'FortnoxAB/changesets-java'
    permissions:
      pull-requests: read
      contents: write
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@05e31511f85b41b11d1cf0ef85d0992719546e2c # v2.21.0
        with:
          egress-policy: audit

      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: true # Needed for pushing new changesets

      - name: Set up JDK 17
        uses: actions/setup-java@dd06d9cba3e5552c54d9f8ea23572deb30010f7c # v6.0.0
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - uses: FortnoxAB/changesets-java-dependabot-action@4084a9bd82d16ec639f15a28fe5eb30696ac571d # main

      - name: Validate
        shell: bash
        run: |
          ls -l .changeset
          git status
